
name: shift_calculator
description: A simple Flutter app for shift calculations.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.0.12

flutter:
  uses-material-design: true
